/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type {
  BroadcastRequest,
  BroadcastResult,
  ConversationInfo,
  CreateGroupRequest,
  CreateGroupResult,
  GroupInfo,
  GroupMemberRequest,
  OkResult,
  ReadConversationRequest,
  ReadConversationResult,
  ReadGroupRequest,
  ReadGroupResult,
  SendRequest,
  SendResult,
} from '@deepseek-ai/dsh-host-intercom/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$696e746572636f6d {
    list: () => Promise<RemoteResult<ConversationInfo[]>>
    groups: () => Promise<RemoteResult<GroupInfo[]>>
    send: (request: SendRequest) => Promise<RemoteResult<SendResult>>
    broadcast: (request: BroadcastRequest) => Promise<RemoteResult<BroadcastResult>>
    readConversation: (request: ReadConversationRequest) => Promise<RemoteResult<ReadConversationResult>>
    readGroup: (request: ReadGroupRequest) => Promise<RemoteResult<ReadGroupResult>>
    createGroup: (request: CreateGroupRequest) => Promise<RemoteResult<CreateGroupResult>>
    addMember: (request: GroupMemberRequest) => Promise<RemoteResult<OkResult>>
    removeMember: (request: GroupMemberRequest) => Promise<RemoteResult<OkResult>>
  }
  interface TypertRemoteMap {
    'intercom/list': () => Promise<RemoteResult<ConversationInfo[]>>
    'intercom/groups': () => Promise<RemoteResult<GroupInfo[]>>
    'intercom/send': (request: SendRequest) => Promise<RemoteResult<SendResult>>
    'intercom/broadcast': (request: BroadcastRequest) => Promise<RemoteResult<BroadcastResult>>
    'intercom/readConversation': (request: ReadConversationRequest) => Promise<RemoteResult<ReadConversationResult>>
    'intercom/readGroup': (request: ReadGroupRequest) => Promise<RemoteResult<ReadGroupResult>>
    'intercom/createGroup': (request: CreateGroupRequest) => Promise<RemoteResult<CreateGroupResult>>
    'intercom/addMember': (request: GroupMemberRequest) => Promise<RemoteResult<OkResult>>
    'intercom/removeMember': (request: GroupMemberRequest) => Promise<RemoteResult<OkResult>>
  }
  interface TypertRemoteNamespaceMap {
    'intercom': TypertRemoteNamespace$696e746572636f6d
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
